CREATE DATABASE hospital_db;
USE hospital_db;

SHOW TABLES;
DESCRIBE doctors;
DESCRIBE billing;
DESCRIBE appointments;
DESCRIBE patients;
DESCRIBE treatments;


------------------------------------------------------------------------------
/*   1. Total Number of Records in Each Table  */

SELECT 
  (SELECT COUNT(*) FROM patients) AS total_patients,
  (SELECT COUNT(*) FROM doctors) AS total_doctors,
  (SELECT COUNT(*) FROM appointments) AS total_appointments,
  (SELECT COUNT(*) FROM treatments) AS total_treatments,
  (SELECT COUNT(*) FROM billing) AS total_bills;
  
  
----------------------------------------------------------------------------------------------------

/*  Top 5 Most Consulted Doctors */

SELECT 
  CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
  d.specialization,
  COUNT(*) AS total_appointments
FROM appointments a
JOIN doctors d ON a.doctor_id = d.doctor_id
GROUP BY d.doctor_id, d.first_name, d.last_name, d.specialization
ORDER BY total_appointments DESC
LIMIT 5;

----------------------------------------------------------------------------------------------

/*  Top 5 Spending Patients */

SELECT 
  CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
  SUM(b.amount) AS total_spent
FROM billing b
JOIN patients p ON b.patient_id = p.patient_id
GROUP BY p.patient_id, p.first_name, p.last_name
ORDER BY total_spent DESC
LIMIT 5;


------------------------------------------------------------------------------------------------------------------

/* Most Common Treatment Types */

SELECT 
  treatment_type,
  COUNT(*) AS frequency
FROM treatments
GROUP BY treatment_type
ORDER BY frequency DESC
LIMIT 5;

---------------------------------------------------------------------------------------------------

/* Monthly Revenue from Billing */

SELECT 
  SUBSTRING(bill_date, 1, 7) AS billing_month,
  SUM(amount) AS monthly_revenue
FROM billing
GROUP BY billing_month
ORDER BY billing_month;

-------------------------------------------------------------------------------------------------------
/* Revenue Generated by Each Doctor */

SELECT 
  CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
  d.specialization,
  SUM(b.amount) AS total_revenue
FROM billing b
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN doctors d ON a.doctor_id = d.doctor_id
GROUP BY d.doctor_id, d.first_name, d.last_name, d.specialization
ORDER BY total_revenue DESC;


------------------------------------------------------------------------------------------------------------------

/* Top 5 Repeat Patients */

SELECT 
  CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
  COUNT(*) AS total_visits
FROM appointments a
JOIN patients p ON a.patient_id = p.patient_id
GROUP BY p.patient_id, p.first_name, p.last_name
HAVING total_visits > 1
ORDER BY total_visits DESC
LIMIT 5;



-------------------------------------------------------------------------------------------------
 /* Most Common Reasons for Hospital Visits */

SELECT 
  reason_for_visit, 
  COUNT(*) AS visit_count
FROM appointments
GROUP BY reason_for_visit
ORDER BY visit_count DESC
LIMIT 10;

-------------------------------------------------------------------------------------------

/* Payment Status Summary */

SELECT 
  payment_status,
  COUNT(*) AS total_bills,
  SUM(amount) AS total_amount
FROM billing
GROUP BY payment_status;


------------------------------------------------------------------------------------------------------

/* Total Monthly Revenue */ 

SELECT 
  DATE_FORMAT(STR_TO_DATE(bill_date, '%Y-%m-%d'), '%Y-%m') AS month,
  SUM(amount) AS total_monthly_revenue
FROM billing
GROUP BY month
ORDER BY month;


----------------------------------------------------------------------------------------


/* High-Cost Treatment Alerts */

SELECT 
  t.treatment_id,
  t.treatment_type,
  t.cost,
  p.first_name,
  p.last_name
FROM treatments t
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN patients p ON a.patient_id = p.patient_id
WHERE t.cost > 10000
ORDER BY t.cost DESC;







